services:
  php-fpm:
    image: php:${PHP_VERSION:-8.3}-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./testing/php:/var/www/html
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5
